// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRLoWKkecvh3bf79_aaovQdBBa2UInKm4',
    appId: '1:194724757632:web:36a639b22015ad28f6e665',
    messagingSenderId: '194724757632',
    projectId: 'frete-grao',
    authDomain: 'frete-grao.firebaseapp.com',
    databaseURL: 'https://frete-grao-default-rtdb.firebaseio.com',
    storageBucket: 'frete-grao.appspot.com',
    measurementId: 'G-JZYH0CP24Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKf180GDttgwO6aQCGzBFAxE6tT5Jm1lc',
    appId: '1:194724757632:android:e6752c6261f2837bf6e665',
    messagingSenderId: '194724757632',
    projectId: 'frete-grao',
    databaseURL: 'https://frete-grao-default-rtdb.firebaseio.com',
    storageBucket: 'frete-grao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkXkb3FfZM8b90hBAR-RaJvHJxqPn-tb4',
    appId: '1:194724757632:ios:6c56642d090d72b1f6e665',
    messagingSenderId: '194724757632',
    projectId: 'frete-grao',
    databaseURL: 'https://frete-grao-default-rtdb.firebaseio.com',
    storageBucket: 'frete-grao.appspot.com',
    iosClientId: '194724757632-m032echhdm0kk6mfm49h6vsl33pmh3sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrierBoost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkXkb3FfZM8b90hBAR-RaJvHJxqPn-tb4',
    appId: '1:194724757632:ios:6c56642d090d72b1f6e665',
    messagingSenderId: '194724757632',
    projectId: 'frete-grao',
    databaseURL: 'https://frete-grao-default-rtdb.firebaseio.com',
    storageBucket: 'frete-grao.appspot.com',
    iosClientId: '194724757632-m032echhdm0kk6mfm49h6vsl33pmh3sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrierBoost',
  );
}
